In [18]:
import numpy as numpy
import pandas as pd

In [19]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [20]:
df.head()

,cgpa,profile_score,placed
0,8,8,1
1,7,9,1
2,6,10,0
3,5,5,0


In [21]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [22]:

model = Sequential()

model.add(Dense(2, activation='linear',input_dim=2))
model.add(Dense(1, activation='linear'))



In [23]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [24]:
model.get_weights()

[array([[-0.9906268, -1.1499442],
        [-0.5776248,  0.568908 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.321308  ],
        [0.20540547]], dtype=float32),
 array([0.], dtype=float32)]

In [25]:
import numpy as np
new_weights = [
    np.array([[0.1, 0.1],
              [0.1, 0.1]], dtype=np.float32),

    np.array([0.1, 0.1], dtype=np.float32),

    np.array([[0.1],
              [0.1]], dtype=np.float32),

    np.array([0.1], dtype=np.float32)
]

In [26]:
model.set_weights(new_weights)

In [27]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0.1, 0.1], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.1], dtype=float32)]

In [28]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='binary_crossentropy')

In [29]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values, epochs=50,verbose=1, batch_size=1)

Epoch 1/50
4/4 [==============================] - 3s 8ms/step - loss: 0.6593
Epoch 2/50
4/4 [==============================] - 0s 9ms/step - loss: 0.6454
Epoch 3/50
4/4 [==============================] - 0s 11ms/step - loss: 0.6430
Epoch 4/50
4/4 [==============================] - 0s 10ms/step - loss: 0.6419
Epoch 5/50
4/4 [==============================] - 0s 8ms/step - loss: 0.6396
Epoch 6/50
4/4 [==============================] - 0s 8ms/step - loss: 0.6362
Epoch 7/50
4/4 [==============================] - 0s 9ms/step - loss: 0.6347
Epoch 8/50
4/4 [==============================] - 0s 11ms/step - loss: 0.6335
Epoch 9/50
4/4 [==============================] - 0s 14ms/step - loss: 0.6324
Epoch 10/50
4/4 [==============================] - 0s 15ms/step - loss: 0.6327
Epoch 11/50
4/4 [==============================] - 0s 54ms/step - loss: 0.6296
Epoch 12/50
4/4 [==============================] - 0s 13ms/step - loss: 0.6288
Epoch 13/50
4/4 [==============================] - 0s 16ms/step - 