In [1]:
import numpy as numpy
import pandas as pd

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [3]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [5]:
import tensorflow as tf

print("TensorFlow:", tf.__version__)

TensorFlow: 2.15.0


In [6]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [18]:

model = Sequential()

model.add(Dense(2, activation='linear',input_dim=2))
model.add(Dense(1, activation='linear'))



In [22]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 2)                 6         
                                                                 
 dense_5 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.get_weights()

[array([[-1.1604049 ,  0.5210856 ],
        [-0.14272797, -0.2998644 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.3788513],
        [ 0.6290883]], dtype=float32),
 array([0.], dtype=float32)]

In [24]:
import numpy as np
new_weights = [
    np.array([[0.1, 0.1],
              [0.1, 0.1]], dtype=np.float32),

    np.array([0.1, 0.1], dtype=np.float32),

    np.array([[0.1],
              [0.1]], dtype=np.float32),

    np.array([0.1], dtype=np.float32)
]

In [25]:
model.set_weights(new_weights)

In [26]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0.1, 0.1], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.1], dtype=float32)]

In [28]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='mean_squared_error')

In [29]:
model.fit(df.iloc[:, :-1].values,df['lpa'].values, epochs=75, batch_size=1)

Epoch 1/75
4/4 [==============================] - 3s 12ms/step - loss: 26.6594
Epoch 2/75
4/4 [==============================] - 0s 8ms/step - loss: 26.3590
Epoch 3/75
4/4 [==============================] - 0s 4ms/step - loss: 26.0295
Epoch 4/75
4/4 [==============================] - 0s 5ms/step - loss: 25.6897
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 25.3407
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 24.9860
Epoch 7/75
4/4 [==============================] - 0s 5ms/step - loss: 24.6334
Epoch 8/75
4/4 [==============================] - 0s 4ms/step - loss: 24.2591
Epoch 9/75
4/4 [==============================] - 0s 5ms/step - loss: 23.8355
Epoch 10/75
4/4 [==============================] - 0s 11ms/step - loss: 23.4411
Epoch 11/75
4/4 [==============================] - 0s 9ms/step - loss: 23.0259
Epoch 12/75
4/4 [==============================] - 0s 8ms/step - loss: 22.6152
Epoch 13/75
4/4 [==============================] - 0s 6ms/s

In [30]:
model.get_weights()

[array([[0.369482  , 0.369482  ],
        [0.36186567, 0.36186567]], dtype=float32),
 array([0.3683302, 0.3683302], dtype=float32),
 array([[0.36722407],
        [0.36722407]], dtype=float32),
 array([0.30224204], dtype=float32)]