In [1]:
import numpy as numpy
import pandas as pd

In [6]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [7]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [8]:
import numpy as np

def initialize_parameters(layer_dims):
    np.random.seed(3)
    
    parameters = {}
    L = len(layer_dims)

    for l in range(1, L):
        parameters['W' + str(l)] = np.ones(
            (layer_dims[l], layer_dims[l-1])
        ) * 0.1
        
        parameters['b' + str(l)] = np.zeros(
            (layer_dims[l], 1)
        )

    return parameters


parameters = initialize_parameters([2, 2, 1])

print(parameters)

{'W1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[0.1, 0.1]]), 'b2': array([[0.]])}


In [10]:
initialize_parameters([2, 2, 1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1, 0.1]]),
 'b2': array([[0.]])}

In [24]:
def linear_forward(A_prev, W, b):
    
    Z = np.dot(W, A_prev) + b
    
    return Z

In [47]:
#forward propagation for L layers

def L_layer_forward(X, parameters):
    
    A = X
    L = len(parameters) // 2   # no. of layers in the neural network
    
    for l in range(1, L + 1):
        A_prev = A
        
        W = parameters['W' + str(l)]
        b = parameters['b' + str(l)]

        #print("A" + str(l-1) + ": ", A_prev)
        #print("W" + str(l) + ": ", W)
        #print("b" + str(l) + ": ", b)

        Z = linear_forward(A_prev, W, b)
        #print("Z" + str(l) + ": ", Z)
        #print("**" * 20)

        A = Z

    return A, A_prev

In [26]:
x=df[['cgpa','profile_score']].values[0].reshape(2,1)
y=df[['lpa']].values[0,0]

# parameters_initialization
parameters = initialize_parameters([2, 2, 1])


print(parameters)


{'W1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[0.1, 0.1]]), 'b2': array([[0.]])}


In [27]:
L_layer_forward(x, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
Z1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1 0.1]]
b2:  [[0.]]
Z2:  [[0.32]]
****************************************


(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [28]:
x

array([[8],
       [8]], dtype=int64)

In [29]:
y

4

In [31]:
(y-0.32)**2

13.5424

In [32]:
def update_parameters(parameters, y, y_hat, A1, X):

    # Output layer
    parameters['W2'][0][0] = parameters['W2'][0][0] + (
        0.001 * 2 * (y - y_hat) * A1[0][0]
    )

    parameters['W2'][0][1] = parameters['W2'][0][1] + (
        0.001 * 2 * (y - y_hat) * A1[1][0]
    )

    parameters['b2'][0][0] = parameters['b2'][0][0] + (
        0.001 * 2 * (y - y_hat)
    )


    # Hidden neuron 1
    parameters['W1'][0][0] = parameters['W1'][0][0] + (
        0.001 * 2 * (y - y_hat) * parameters['W2'][0][0] * X[0][0]
    )

    parameters['W1'][0][1] = parameters['W1'][0][1] + (
        0.001 * 2 * (y - y_hat) * parameters['W2'][0][0] * X[1][0]
    )

    parameters['b1'][0][0] = parameters['b1'][0][0] + (
        0.001 * 2 * (y - y_hat) * parameters['W2'][0][0]
    )


    # Hidden neuron 2
    parameters['W1'][1][0] = parameters['W1'][1][0] + (
        0.001 * 2 * (y - y_hat) * parameters['W2'][0][1] * X[0][0]
    )

    parameters['W1'][1][1] = parameters['W1'][1][1] + (
        0.001 * 2 * (y - y_hat) * parameters['W2'][0][1] * X[1][0]
    )

    parameters['b1'][1][0] = parameters['b1'][1][0] + (
        0.001 * 2 * (y - y_hat) * parameters['W2'][0][1]
    )

    return parameters

In [33]:
x=df[['cgpa','profile_score']].values[0].reshape(2,1)
y=df[['lpa']].values[0,0]

parameters = initialize_parameters([2, 2, 1])
y_hat, A1 = L_layer_forward(x, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
Z1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1 0.1]]
b2:  [[0.]]
Z2:  [[0.32]]
****************************************


In [ ]:
y_hat=y_hat[0][0]

In [35]:
A1

array([[1.6],
       [1.6]])

In [36]:
update_parameters(parameters,y,y_hat,A1,x)

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776, 0.111776]]),
 'b2': array([[0.00736]])}

In [37]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776, 0.111776]]),
 'b2': array([[0.00736]])}

In [38]:
x=df[['cgpa','profile_score']].values[1].reshape(2,1)
y=df[['lpa']].values[1][0]

parameters = initialize_parameters([2, 2, 1])
y_hat, A1 = L_layer_forward(x, parameters)

A0:  [[7]
 [9]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
Z1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1 0.1]]
b2:  [[0.]]
Z2:  [[0.32]]
****************************************


In [39]:
update_parameters(parameters,y,y_hat,A1,x)

C:\Users\Kshama\AppData\Local\Temp\ipykernel_28676\2055653513.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (
C:\Users\Kshama\AppData\Local\Temp\ipykernel_28676\2055653513.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][1] = parameters['W2'][0][1] + (
C:\Users\Kshama\AppData\Local\Temp\ipykernel_28676\2055653513.py:12: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0]

{'W1': array([[0.10753323, 0.10968558],
        [0.10753323, 0.10968558]]),
 'b1': array([[0.00107618],
        [0.00107618]]),
 'W2': array([[0.114976, 0.114976]]),
 'b2': array([[0.00936]])}

In [40]:
x=df[['cgpa','profile_score']].values[2].reshape(2,1)
y=df[['lpa']].values[2][0]

parameters = initialize_parameters([2, 2, 1])
y_hat, A1 = L_layer_forward(x, parameters)

A0:  [[ 6]
 [10]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
Z1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1 0.1]]
b2:  [[0.]]
Z2:  [[0.32]]
****************************************


In [41]:
update_parameters(parameters,y,y_hat,A1,x)

C:\Users\Kshama\AppData\Local\Temp\ipykernel_28676\2055653513.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (
C:\Users\Kshama\AppData\Local\Temp\ipykernel_28676\2055653513.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][1] = parameters['W2'][0][1] + (
C:\Users\Kshama\AppData\Local\Temp\ipykernel_28676\2055653513.py:12: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0]

{'W1': array([[0.10805488, 0.11342479],
        [0.10805488, 0.11342479]]),
 'b1': array([[0.00134248],
        [0.00134248]]),
 'W2': array([[0.118176, 0.118176]]),
 'b2': array([[0.01136]])}

In [42]:
x=df[['cgpa','profile_score']].values[3].reshape(2,1)
y=df[['lpa']].values[3][0]

parameters = initialize_parameters([2, 2, 1])
y_hat, A1 = L_layer_forward(x, parameters)

A0:  [[ 5]
 [12]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
Z1:  [[1.7]
 [1.7]]
****************************************
A1:  [[1.7]
 [1.7]]
W2:  [[0.1 0.1]]
b2:  [[0.]]
Z2:  [[0.34]]
****************************************


In [43]:
update_parameters(parameters,y,y_hat,A1,x)

C:\Users\Kshama\AppData\Local\Temp\ipykernel_28676\2055653513.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (
C:\Users\Kshama\AppData\Local\Temp\ipykernel_28676\2055653513.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][1] = parameters['W2'][0][1] + (
C:\Users\Kshama\AppData\Local\Temp\ipykernel_28676\2055653513.py:12: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0]

{'W1': array([[0.10816809, 0.11960342],
        [0.10816809, 0.11960342]]),
 'b1': array([[0.00163362],
        [0.00163362]]),
 'W2': array([[0.122644, 0.122644]]),
 'b2': array([[0.01332]])}

In [45]:
parameters

{'W1': array([[0.27790431, 0.40579137],
        [0.27790431, 0.40579137]]),
 'b1': array([[0.0295198],
        [0.0295198]]),
 'W2': array([[0.46411039, 0.46411039]]),
 'b2': array([[0.11664796]])}

In [48]:
# epochs implementation

parameters = initialize_parameters([2, 2, 1])

epochs = 5

for i in range(epochs):

    Loss = []

    for j in range(df.shape[0]):

        X = df[['cgpa', 'profile_score']].values[j].reshape(2, 1)

        y = df[['lpa']].values[j][0]

        # Forward propagation
        y_hat, A1 = L_layer_forward(X, parameters)

        y_hat = y_hat[0][0]

        # Update parameters
        update_parameters(parameters, y, y_hat, A1, X)

        # Store loss
        Loss.append((y - y_hat) ** 2)

    # Print loss after completing one epoch
    print("Epoch-" + str(i + 1) + ", Loss: " + str(np.array(Loss).mean()))

parameters

Epoch-1, Loss: 26.249691774703265
Epoch-2, Loss: 19.19634375189233
Epoch-3, Loss: 9.702531836210806
Epoch-4, Loss: 3.027416260208091
Epoch-5, Loss: 1.0597082587765176


{'W1': array([[0.27790431, 0.40579137],
        [0.27790431, 0.40579137]]),
 'b1': array([[0.0295198],
        [0.0295198]]),
 'W2': array([[0.46411039, 0.46411039]]),
 'b2': array([[0.11664796]])}